"""empty message

Revision ID: 4c2ffd96f1a2
Revises: 948591fdc30f
Create Date: 2021-08-25 20:50:17.584093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c2ffd96f1a2'
down_revision = '948591fdc30f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'stories', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stories', type_='foreignkey')
    # ### end Alembic commands ###
