"""empty message

Revision ID: 948591fdc30f
Revises: ffdc0a98111c
Create Date: 2021-08-12 18:07:50.897596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '948591fdc30f'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('storyJSON', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stories')
    # ### end Alembic commands ###
