"""empty message

Revision ID: 9cf3690ec670
Revises: cce60c9bc32d
Create Date: 2021-08-26 16:07:07.507943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cf3690ec670'
down_revision = 'cce60c9bc32d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('test', sa.String(length=45), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'test')
    # ### end Alembic commands ###
