"""empty message

Revision ID: a641f481bcef
Revises: 45d422c29beb
Create Date: 2021-09-23 19:29:23.992918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a641f481bcef'
down_revision = '45d422c29beb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('acceptance_criteria', 'monkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('acceptance_criteria', sa.Column('monkey', sa.VARCHAR(length=2), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
