"""empty message

Revision ID: 373aa985ac34
Revises: 74a9afe2a280
Create Date: 2021-09-08 13:28:33.035270

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '373aa985ac34'
down_revision = '74a9afe2a280'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues', sa.Column('user', sa.String(length=100), nullable=False))
    op.add_column('issues', sa.Column('action', sa.String(length=255), nullable=True))
    op.add_column('issues', sa.Column('result', sa.String(length=255), nullable=True))
    op.add_column('questions', sa.Column('feature_id', sa.Integer(), nullable=False))
    op.drop_constraint('questions_issue_id_fkey', 'questions', type_='foreignkey')
    op.create_foreign_key(None, 'questions', 'features', ['feature_id'], ['id'])
    op.drop_column('questions', 'issue_id')
    op.add_column('stories', sa.Column('app_name', sa.String(length=100), nullable=False))
    op.drop_column('stories', 'storyJSON')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stories', sa.Column('storyJSON', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('stories', 'app_name')
    op.add_column('questions', sa.Column('issue_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.create_foreign_key('questions_issue_id_fkey', 'questions', 'issues', ['issue_id'], ['id'])
    op.drop_column('questions', 'feature_id')
    op.drop_column('issues', 'result')
    op.drop_column('issues', 'action')
    op.drop_column('issues', 'user')
    # ### end Alembic commands ###
