"""empty message

Revision ID: c7c670250621
Revises: 373aa985ac34
Create Date: 2021-09-10 17:31:41.052711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7c670250621'
down_revision = '373aa985ac34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('issues', 'user_story')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues', sa.Column('user_story', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
