# This is a basic workflow to help you get started with Actions

name: CI

name: User Story Generator

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
    steps:
    - uses: actions/checkout@v2
    - name: Login to Heroku Container registry
      run: heroku container:login
    - name: Build and push
      run: heroku container:push -a muser-story-generator web
    - name: Release
      run: heroku container:release -a user-story-generator web
